name: Deploy github page
run-name: ${{ github.actor }}
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@4
      - name: Install dpendencies
        run: pnpm install
      - name: Build page
        run: pnpm run build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-actions@4
        with:
          branch: gh-pages
          folder: dist
